1章

In [4]:
#1
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

#2
from scipy import sparse

eye = np.eye(4)
print("NumPy array:\n{}".format(eye))

#3
sparse_matrix = sparse.csr_matrix(eye)
print("\nScipy sparse CSR matrix:\n{}".format(sparse_matrix))

x:
[[1 2 3]
 [4 5 6]]
NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Scipy sparse CSR matrix:
  (np.int32(0), np.int32(0))	1.0
  (np.int32(1), np.int32(1))	1.0
  (np.int32(2), np.int32(2))	1.0
  (np.int32(3), np.int32(3))	1.0
